# Generated by Django 2.0.2 on 2018-02-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='null')),
                ('student_num', models.IntegerField(verbose_name=0)),
                ('felica_id', models.CharField(max_length=100, verbose_name='null')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='users',
            field=models.ManyToManyField(to='moneymanager.User'),
        ),
    ]
