# Generated by Django 2.0.2 on 2018-02-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='users',
        ),
        migrations.AlterField(
            model_name='user',
            name='felica_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_num',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
