# Generated by Django 2.0.2 on 2018-02-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanager', '0002_auto_20180220_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='felica_id',
            field=models.CharField(max_length=100, verbose_name='FelicaID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_num',
            field=models.IntegerField(verbose_name='学籍番号'),
        ),
    ]
